# Generated by Django 4.2.26 on 2025-11-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_product_size_remove_product_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(choices=[('Apple', 'Apple'), ('LG', 'LG'), ('Samsong', 'Samsong'), ('Vivo', 'Vivo'), ('Oppo', 'Oppo')], max_length=15, unique=True),
        ),
    ]
